export const Types = {
    SEARCHBARVISIBLE : "SEARCHBARVISIBLE",
    CHANGEURI : "CHANGEURI",
    CHANGEITEMUSER: "CHANGEITEMUSER",
    PHOTOLOADAVATAR: "PHOTOLOADAVATAR",
    LOADUSERS: "LOADUSERS",
    CHANGELISTUSERS: "CHANGELISTUSERS",
    SETAUTHUSER: "SETAUTHUSER",
    SETSERVERERRORMSN: "SETSERVERERRORMSN"
}